//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Login_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Login_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Jamie\AppData\Local\Temp\1E97EDDB40184E35504EB4FA4C705F50BC5A\2\BlogWebsite\BlogWebsite\Views\Home\Login.cshtml"
  
    Layout = "~/Views/Shared/_BlogWebsiteLayout.cshtml";


#line default
#line hidden
}
}
}
